---

  # Add Docker GPG apt Key
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  # Add Docker Repository
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  # Update apt and install docker-ce
  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
    become: true

  # Install Docker Module for Python
  - name: Install Docker Module for Python
    pip:
      name: docker

  # Pull default Docker image
  - name: Pull default Docker image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull

  # Creates the number of containers defined by the variable create_containers, using values from vars file
  - name: Create default containers
    docker_container:
      name: "{{ default_container_name }}{{ item }}"
      image: "{{ default_container_image }}"
      command: "{{ default_container_command }}"
      state: present
    with_sequence: count={{ create_containers }}

  # Ensure Docker service is installed and restarted
  - name: Ensure Docker service is installed and restarted
    service:
      name: docker
      state: restarted
      enabled: yes

  # Install Docker Compose
  - name: Install Docker Compose
    pip:
      name: docker-compose

  # Install Docker Compose
  - name: Add vagrant user to docker group.
    user:
      name: vagrant
      groups: docker
      append: yes
    become: true
