---
- hosts: all
  tasks:
    # Update and upgrade apt packages
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
        autoremove: yes
        autoclean: yes
        purge: yes
    # Install add-apt-repostory
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest
    # Install list of dependency packages
    - name: Install list of dependency packages
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - build-essential
          - gcc
          - git
          - git-core
          - virtualbox-guest-dkms
          - virtualbox-guest-utils
          - virtualbox-guest-x11
