# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.box_version = "20210701.01"
  config.vm.hostname = "ubuntu-bionic-beaver"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-bionic-beaver"
    vb.gui = true
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize [ "modifyvm", :id, "--clipboard", "bidirectional"]
  end
  # Run ansible on vagrant host
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./provision/ansible/playbook.yml"
    ansible.verbose = true
  end
  # Run shell script on vagrant host
  config.vm.provision "shell", path: "./provision/shell/test.sh"
end


