# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.box_version = "20190801.01"
  config.vm.hostname = "ubuntu-bionic-beaver"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    # Set virtual machine name
    vb.name = "ubuntu-bionic-beaver"
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    # disable generating ubuntu-bionic-18.04-cloudimg-console.log file in the shared folder
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  # Run ansible from the vagrant host
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./provision/ansible/playbook.yml"
    ansible.verbose = true
  end
end


