---
- hosts: all
  tasks:
    # Update and upgrade apt packages
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
        autoremove: yes
        autoclean: yes
        purge: yes
    # Install add-apt-repostory
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest
    # Install Open JDK 8
    - name: Install openJDK 8
      become: yes
      apt:
        name: ['openjdk-8-jdk','openjdk-8-jre']
        state: latest
    # Set update-java-alternatives
    - name: Set update-java-alternatives
      become: yes
      shell: update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64
    # Set JAVA_HOME environment variable
    - name: Set JAVA_HOME environment variable
      lineinfile:
        dest: /home/vagrant/.bashrc
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'export JAVA_HOME.*', line: 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' }
        - { regexp: 'export PATH=$PATH:$JAVA_HOME/bin', line: 'export PATH=$PATH:$JAVA_HOME/bin' }
    # Install list of dependency packages
    - name: Install list of dependency packages
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - build-essential
          - gcc
          - git
          - git-core
          - virtualbox-guest-dkms
          - virtualbox-guest-utils
          - virtualbox-guest-x11
