---
- hosts: all
  tasks:
    # ---- JAVA 8
    - name: Install java 8 preresequesits
      apt: name=python-software-properties
    - name: Add Java 8 repository
      apt_repository: repo='ppa:webupd8team/java'
    - name: Agree to oracle license
      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
    - name: Install Java 8
      apt: name=oracle-java8-installer force=yes
    - name: set JAVA_HOME environment variable
      lineinfile:
        dest: /home/ubuntu/.bashrc
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'export JAVA_HOME.*', line: 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle' }
        - { regexp: 'export PATH=$PATH:$JAVA_HOME/bin', line: 'export PATH=$PATH:$JAVA_HOME/bin' }
    # ---- END JAVA 8
